
DIRS= practica-1 practica-2 practica-3

GCC=gcc


all:	
	make -C practica-1
	make -C practica-2
	make -C practica-3
	make -C libraries

clean: 
	make -C practica-1 clean
	make -C practica-2 clean
	make -C practica-3 clean
	make -C libraries clean

